# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
import random
import time
import os
import requests
import json

if os.name == "nt":
    os.system("cls")
else:
    os.system("clear")

token = "683373916709847122"

while True:
  message = input("mc.traancraft.nl ")
  message2 = message

  loop = ""
  for n in message:
      loop += n
      status_data = json.dumps(
          {
              "custom_status":
              {
                  "text": loop
              }
          }
      )

      r = requests.patch("https://discordapp.com/api/v6/users/@me/settings", headers={"Authorization": token, "Content-Type": "application/json"}, data=status_data)
      print(loop + "\r", end="")
      time.sleep(0.1)

  message = " " + message + " "

  for n in message:
      count = 2
      while count > 0:
          message += message[0]
          message = message[1:]
          count -= 1
          
          status_data = json.dumps(
              {
                  "custom_status":
                  {
                      "text": message
                  }
              }
          )

          r = requests.patch("https://discordapp.com/api/v6/users/@me/settings", headers={"Authorization": token, "Content-Type": "application/json"}, data=status_data)
          print(message + "\r", end="")
          time.sleep(0.09)

  message = message2

  for n in range(len(message)):
      message = message.replace(message[random.randint(0, len(message) - 1)], " ")
      status_data = json.dumps(
          {
              "custom_status":
              {
                  "text": message
              }
          }
      )

      r = requests.patch("https://discordapp.com/api/v6/users/@me/settings", headers={"Authorization": token, "Content-Type": "application/json"}, data=status_data)
      print(message + "\r", end="")
      time.sleep(0.2)
